pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:cristianccori/mirror-repository.git
          - cd mirror-repository.git
          - git push --mirror git@github.com:cristianccoritz/Mirror-Repository.git